### PR TITLE
fixes elixir-stream app to run on elixir 1.1.0

### PR DESCRIPTION
**Pull request by mindreframer**
Problem: the app did not compile

Solution: 
- update timex to 0.19.5 (last before 1.0.0-rc) 
- update :basic_auth config for dev/test environments to include the full config path: :elixir_stream, :basic_auth

### CODE REVIEW

**Comment by janjiss** [comment]
Kudos @mindreframer!

**Comment by mindreframer** [comment]
Wow! The quickest pull request merge ever! :+1:

**Comment by janjiss** [comment]
@mindreframer GitHub notifications + Me at the keyboard + Easy to understand PR = Magic :)

**Comment by mindreframer** [comment]
I just love magic!  :) 

I just love magic!

**Pull request merged**
